jwt:
   secret: hfdjlaaskjllslkajsajskjs
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reto1
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org:
      hibernate:
        SQL: debug
