jwt:
  secret: hfdjlaaskjllslkajsajskjs

server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reto2
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
